'use client';

import './globals.css';
import { Montserrat } from 'next/font/google';
import { ChakraProvider } from '@chakra-ui/react';
import { CacheProvider } from '@chakra-ui/next-js';
import Header from '@/components/Header/Header';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Стоматологический центр ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <body className={montserrat.className}>
        <CacheProvider>
          <ChakraProvider>
            <Header />
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
